/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Product,
  ProductForm
} from './model';

export const getOpenAPIDefinition = (axiosInstance: AxiosInstance = axios.default) => {
const getProducts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product[]>> => {
    return axiosInstance.get(
      `http://localhost:8080/api/products`,options
    );
  }

const createProduct = (
    productForm: ProductForm, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product>> => {
    return axiosInstance.post(
      `http://localhost:8080/api/products`,
      productForm,options
    );
  }

const deleteProduct = (
    productId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `http://localhost:8080/api/products/${productId}`,options
    );
  }

return {getProducts,createProduct,deleteProduct}};
export type GetProductsResult = AxiosResponse<Product[]>
export type CreateProductResult = AxiosResponse<Product>
export type DeleteProductResult = AxiosResponse<void>
