/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Product {
  id?: number;
  name?: string;
  description?: string;
  price?: number;
}
