/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProductForm {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  /**
     * @minimum 0
     * @maximum 1000000
     */
  price: number;
}
